            case .systemDiagnostics:
                GenericBackendView(route: .systemDiagnostics)
            case .farmBureau:
                GenericBackendView(route: .farmBureau)
            case .serverAIConsole:
                GenericBackendView(route: .serverAIConsole)
            case .selfRepair:
                GenericBackendView(route: .selfRepair)
            case .knowledgeVault:
                GenericBackendView(route: .knowledgeVault)
            case .agiDispatcher:
                GenericBackendView(route: .agiDispatcher)
            case .androidBuilder:
                GenericBackendView(route: .androidBuilder)
            case .iosBuilder:
                GenericBackendView(route: .iosBuilder)
            case .swiftGenerator:
                GenericBackendView(route: .swiftGenerator)
            case .businessCalculator:
                GenericBackendView(route: .businessCalculator)
            case .blueprintGenerator:
                GenericBackendView(route: .blueprintGenerator)
